version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: app.log
    maxBytes: 10_485_760  # 10 MB
    backupCount: 5
    encoding: utf8

loggers:
  app:
      level: INFO
      handlers: [console, file]
      propagate: false
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [console, file]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: false

  sqlalchemy.engine:
    level: INFO   # Change to DEBUG to log all SQL queries
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
